name = "Nixie"
author = "Xelorion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "089ac2f73b2fbd519b3c8a1b893986ec71a825c320350f13b0de00989665c724"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
