name = "Nixie"
author = "Xelorion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1e2ef6f2e84bc388e31106dbb542005486dcb5b3f53cb52d9c05c3294256d44"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
